locales/en/common.json, locales/en/devices.json, locales/pirate/common.json
Updated translation to match the frontend translation pull request
=> feat: update translations for new header

locales/en/common.json, locales/en/users.json
Updates to translations keys needed for the new user management ui
=> feat: manage ui

locales/en/common.json
Translations for no matches for search page
=> feat: No matches

locales/en/common.json
Translations needed for https://github.com/Zydex/asiga-api-backend/pull/91/files
=> feat: added partMarkAsUploadedIncorrectState translation AWF-439

locales/en/inbox.json
[YouTrack Issue: WP-65](https://zydex.youtrack.cloud/issue/WP-65/Inbox-Part-Details-Panel-Viewer)
Includes translations that appear in the side panel when a part is selected in the inbox.
=> WP-65: Inbox Part Inspector / Details

locales/en/inbox.json
Changes:
- Added drag and drop inbox label
=> WP-59: Drag and drop uploads

locales/en/inbox.json
Note: Although some translations are removed - they are from the inbox page which is yet to be published and is safe to be discarded.
=> WP-64: Inbox functional tabs

locales/en/inbox.json
For [PR WP-85](https://github.com/Zydex/asiga-web-portal/pull/83)
=> WP-85: Added 'Upload cancelled' translation

locales/en/devices.json, locales/en/inbox.json, locales/en/parts.json
Added missing page title translations for (Inbox, Parts and Devices pages).
=> Fix: Added page titles

locales/en/timeline.json
=> feat: Timeline translations

locales/en/inbox.json
=> feat: Denture AOX

locales/en/jobs.json
feat(jobs.json): added 'source' label and respective 'external' value
Required for https://github.com/Zydex/asiga-i18n/pull/52
=>  feat: AWF-812 Select Jobs in Timeline

locales/en/parts.json
Jira issue: [AWF-930](https://asiga.atlassian.net/browse/AWF-930?atlOrigin=eyJpIjoiNDE5MmQ5YzFmYzg1NGY2ZGJkZTY2ZjViM2JlMjA2YWQiLCJwIjoiaiJ9)
Added all of the part status' from David's latest design (from [AWF-845](https://asiga.atlassian.net/browse/AWF-845?atlOrigin=eyJpIjoiMWFiMGRhODYwYjY0NDE3OTkyZDc1NWExZTVhZTA3NTEiLCJwIjoiaiJ9)):
[AWF-930]: https://asiga.atlassian.net/browse/AWF-930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AWF-845]: https://asiga.atlassian.net/browse/AWF-845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AWF-930 Part Checklist Statuses

locales/en/inbox.json
feat(inbox.json): added details panel subtitle for part progress field
=> fix: AWF-930 Added Part Progress Status Field Title

locales/en/templates.json
feat: added message text for empty templates table
=> feat: AWF-1061 templates table empty state text

locales/en/templates.json
Jira: [AWF-1255](https://asiga.atlassian.net/browse/AWF-1255?atlOrigin=eyJpIjoiMTMzOTg0NWI0YmY3NGIzOGI4YjI1YWUxYTlhMmQ2NGQiLCJwIjoiaiJ9)
Required for: [PR-279](https://github.com/Zydex/asiga-web-portal/pull/279)
[AWF-1255]: https://asiga.atlassian.net/browse/AWF-1255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AWF-1255 outdated templates translations

locales/en/jobs.json
Required for https://github.com/Zydex/asiga-web-portal/pull/285
=> feat: added material label for job information

locales/en/apps.json, locales/en/common.json, locales/en/devices.json, locales/en/inbox.json, locales/en/jobs.json, locales/en/materials.json, locales/en/parts.json, locales/en/timeline.json, locales/en/users.json
Jira: [AWF-1279](https://asiga.atlassian.net/browse/AWF-1279?atlOrigin=eyJpIjoiOWIxZDNkNDBiNzRiNDcxM2JlODA0Nzc0MmNiNjFlYmEiLCJwIjoiaiJ9)
Required for: [Asiga-web-portal PR-284](https://github.com/Zydex/asiga-web-portal/pull/284)
[AWF-1279]: https://asiga.atlassian.net/browse/AWF-1279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AWF-1279 tab tooltips

locales/en/jobs.json, locales/en/materials.json
Jira issue: [AWF-1230](https://asiga.atlassian.net/browse/AWF-1073?atlOrigin=eyJpIjoiZjA3OTAzOGZmNTY2NDExODg1NTMxZjI3ZDY2YzY2ZmIiLCJwIjoiaiJ9)
Required for: https://github.com/Zydex/asiga-web-portal/pull/287
[AWF-1230]: https://asiga.atlassian.net/browse/AWF-1230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AWF-1230 table empty states translations

locales/en/common.json, locales/en/jobs.json
Jira:  [AWF-1292](https://asiga.atlassian.net/browse/AWF-1292?atlOrigin=eyJpIjoiY2M4YjJiN2RjMzkxNDEwMDg1NzkzZmM5ZjNlN2U2ZDYiLCJwIjoiaiJ9)
Required for: [PR289](https://github.com/Zydex/asiga-web-portal/pull/289)
[AWF-1292]: https://asiga.atlassian.net/browse/AWF-1292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat:  AWF-1292 provisional job translations

locales/en/parts.json
Jira: [AWF-1267](https://asiga.atlassian.net/browse/AWF-1267?atlOrigin=eyJpIjoiMWY3NzBiZDc5NjlmNGY0ZjllZGMzNDgwMzMxNjhjYzEiLCJwIjoiaiJ9)
Required for: https://github.com/Zydex/asiga-web-portal/pull/296
[AWF-1267]: https://asiga.atlassian.net/browse/AWF-1267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AWF-1267 part progress tooltips

locales/en/common.json
Jira: [AWF-959](https://asiga.atlassian.net/browse/AWF-959)
Required For: https://github.com/Zydex/asiga-web-portal/pull/299
[AWF-959]: https://asiga.atlassian.net/browse/AWF-959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(common.json): Add entries for not found error page

locales/en/devices.json
Jira: https://asiga.atlassian.net/browse/AWF-559
Required For: https://github.com/Zydex/asiga-web-portal/pull/303
=> feat: AWF-559 add label "Status" for use instead of "Paused"

locales/en/devices.json
Jira: [AWF-818](https://asiga.atlassian.net/browse/AWF-818?atlOrigin=eyJpIjoiMWI1MTQ1OWNhNmE2NGI2ZDg1NThjNjVlNDBmYmI5NmIiLCJwIjoiaiJ9)
Required for: [PR-306](https://github.com/Zydex/asiga-web-portal/pull/306)
[AWF-818]: https://asiga.atlassian.net/browse/AWF-818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AWF-818]: https://asiga.atlassian.net/browse/AWF-818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AWF-818 timeline printer card 'more' menu

locales/en-au/templates.json
Jira: [AWF-1465](https://asiga.atlassian.net/browse/AWF-1465)
Required for: [AWF-PR-327](https://github.com/Zydex/asiga-web-portal/pull/327)
[AWF-1465]: https://asiga.atlassian.net/browse/AWF-1465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AWF-1465 fast print mode and separation detect translations
